---
title: "Unit 8"
author: "Pejal Rath"
date: "`r Sys.Date()`"
output: html_document
---




#1.	How many breweries are present in each state?

library(e1071)
library(tm) #text mining library provides the stopwords() function
library(tidyr)
library(plyr)
library(jsonlite)
library(dplyr)
library(tidyverse)
library(mvtnorm)
library(caret)
library(class)
library(ggplot2)
library(plotly)
library(ggthemes)

beer=read.csv(file.choose(),header = TRUE)
brewer=read.csv(file.choose(),header = TRUE)

brewer %>% ggplot(aes(x=State,fill=State))+geom_histogram(stat="count")+theme(legend.position = "none")
brewerByState=brewer %>% count(State)
colnames(brewerByState)[2]="Count"

#3. Address the missing values in each column.
#Fill IBU missing value
set.seed(5)
IBU_na=which(is.na(beer$IBU))
IBU_fill=sample(4:138, 1005,replace=TRUE)
for(i in 1:1005)
{
  beer$IBU[IBU_na[i]]=IBU_fill[i]
}
#Fill ABV missing value
set.seed(5)
ABV_na=which(is.na(beer$ABV))
ABV_fill=sample(0.001:0.128, 62,replace=TRUE)
for(i in 1:62)
{
  beer$ABV[ABV_na[i]]=ABV_fill[i]
}
# Change Ounces to factor type
beer$Ounces=factor(beer$Ounces)

#4.	Compute the median alcohol content and international bitterness unit for each state. Plot a bar chart to compare.
beer_data <- merge(beer,brewer, by.x="Brewery_id",by.y="Brew_ID")
colnames(beer_data)[2]="BeerName"
colnames(beer_data)[8]="BreweryName"
#beer_data$ABV=as.numeric(beer_data$ABV)
summary_ABVIBU<- beer_data %>% group_by(State) %>% summarize(median_ABV = median(ABV),median_IBU = median(IBU))


summary_ABVIBU %>% ggplot(aes(x=State))+geom_bar(aes(y=median_IBU),stat="identity",fill="Red")+labs(title = "Median IBU by State", x = "State",y = "Median IBU") +theme_bw()

summary_ABVIBU %>% ggplot(aes(x=State))+geom_bar(aes(y=median_ABV),stat="identity",fill="blue")+labs(title = "Median Alcohol Content by State", x = "State",y = "Median Alcohol Content") +theme_bw()

#5

beer_data[which.max(beer_data$ABV),]$State

beer_data[which.max(beer_data$IBU),]$State


#7 
ggplot(beer_data, aes(x = ABV, y = IBU)) +
  geom_point() +
  labs(x = "Alcohol Content", y = "Bitterness")+geom_smooth()
  
# Yes, there is an apparent relationship between the bitterness of the beer and its alcoholic content. Base on visualization, there are evidences to show the higher alcohol content then the beer also has higher IBU.
